/*
 * This file is generated by jOOQ.
 */
package ru.citycheck.core.domain.db.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import ru.citycheck.core.domain.db.tables.IssueDocument;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IssueDocumentRecord extends UpdatableRecordImpl<IssueDocumentRecord> implements Record3<Long, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.issue_document.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.issue_document.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.issue_document.document_path</code>.
     */
    public void setDocumentPath(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.issue_document.document_path</code>.
     */
    public String getDocumentPath() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.issue_document.content_type</code>.
     */
    public void setContentType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.issue_document.content_type</code>.
     */
    public String getContentType() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return IssueDocument.ISSUE_DOCUMENT.ID;
    }

    @Override
    public Field<String> field2() {
        return IssueDocument.ISSUE_DOCUMENT.DOCUMENT_PATH;
    }

    @Override
    public Field<String> field3() {
        return IssueDocument.ISSUE_DOCUMENT.CONTENT_TYPE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getDocumentPath();
    }

    @Override
    public String component3() {
        return getContentType();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getDocumentPath();
    }

    @Override
    public String value3() {
        return getContentType();
    }

    @Override
    public IssueDocumentRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public IssueDocumentRecord value2(String value) {
        setDocumentPath(value);
        return this;
    }

    @Override
    public IssueDocumentRecord value3(String value) {
        setContentType(value);
        return this;
    }

    @Override
    public IssueDocumentRecord values(Long value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IssueDocumentRecord
     */
    public IssueDocumentRecord() {
        super(IssueDocument.ISSUE_DOCUMENT);
    }

    /**
     * Create a detached, initialised IssueDocumentRecord
     */
    public IssueDocumentRecord(Long id, String documentPath, String contentType) {
        super(IssueDocument.ISSUE_DOCUMENT);

        setId(id);
        setDocumentPath(documentPath);
        setContentType(contentType);
    }
}
