/*
 * This file is generated by jOOQ.
 */
package ru.citycheck.core.domain.db.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;

import ru.citycheck.core.domain.db.tables.Issue;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IssueRecord extends UpdatableRecordImpl<IssueRecord> implements Record14<Long, String, String, String, Long, String, Long, Long, Long, String, String, String, Double, Double> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.issue.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.issue.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.issue.description</code>.
     */
    public void setDescription(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.issue.description</code>.
     */
    public String getDescription() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.issue.status</code>.
     */
    public void setStatus(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.issue.status</code>.
     */
    public String getStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.issue.priority</code>.
     */
    public void setPriority(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.issue.priority</code>.
     */
    public String getPriority() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.issue.category_id</code>.
     */
    public void setCategoryId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.issue.category_id</code>.
     */
    public Long getCategoryId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.issue.reporter_id</code>.
     */
    public void setReporterId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.issue.reporter_id</code>.
     */
    public String getReporterId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.issue.assignee_id</code>.
     */
    public void setAssigneeId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.issue.assignee_id</code>.
     */
    public Long getAssigneeId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.issue.created_at</code>.
     */
    public void setCreatedAt(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.issue.created_at</code>.
     */
    public Long getCreatedAt() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.issue.updated_at</code>.
     */
    public void setUpdatedAt(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.issue.updated_at</code>.
     */
    public Long getUpdatedAt() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.issue.document_path</code>.
     */
    public void setDocumentPath(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.issue.document_path</code>.
     */
    public String getDocumentPath() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.issue.content_type</code>.
     */
    public void setContentType(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.issue.content_type</code>.
     */
    public String getContentType() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.issue.actuality_status</code>.
     */
    public void setActualityStatus(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.issue.actuality_status</code>.
     */
    public String getActualityStatus() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.issue.location_lat</code>.
     */
    public void setLocationLat(Double value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.issue.location_lat</code>.
     */
    public Double getLocationLat() {
        return (Double) get(12);
    }

    /**
     * Setter for <code>public.issue.location_lon</code>.
     */
    public void setLocationLon(Double value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.issue.location_lon</code>.
     */
    public Double getLocationLon() {
        return (Double) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<Long, String, String, String, Long, String, Long, Long, Long, String, String, String, Double, Double> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Long, String, String, String, Long, String, Long, Long, Long, String, String, String, Double, Double> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Issue.ISSUE.ID;
    }

    @Override
    public Field<String> field2() {
        return Issue.ISSUE.DESCRIPTION;
    }

    @Override
    public Field<String> field3() {
        return Issue.ISSUE.STATUS;
    }

    @Override
    public Field<String> field4() {
        return Issue.ISSUE.PRIORITY;
    }

    @Override
    public Field<Long> field5() {
        return Issue.ISSUE.CATEGORY_ID;
    }

    @Override
    public Field<String> field6() {
        return Issue.ISSUE.REPORTER_ID;
    }

    @Override
    public Field<Long> field7() {
        return Issue.ISSUE.ASSIGNEE_ID;
    }

    @Override
    public Field<Long> field8() {
        return Issue.ISSUE.CREATED_AT;
    }

    @Override
    public Field<Long> field9() {
        return Issue.ISSUE.UPDATED_AT;
    }

    @Override
    public Field<String> field10() {
        return Issue.ISSUE.DOCUMENT_PATH;
    }

    @Override
    public Field<String> field11() {
        return Issue.ISSUE.CONTENT_TYPE;
    }

    @Override
    public Field<String> field12() {
        return Issue.ISSUE.ACTUALITY_STATUS;
    }

    @Override
    public Field<Double> field13() {
        return Issue.ISSUE.LOCATION_LAT;
    }

    @Override
    public Field<Double> field14() {
        return Issue.ISSUE.LOCATION_LON;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getDescription();
    }

    @Override
    public String component3() {
        return getStatus();
    }

    @Override
    public String component4() {
        return getPriority();
    }

    @Override
    public Long component5() {
        return getCategoryId();
    }

    @Override
    public String component6() {
        return getReporterId();
    }

    @Override
    public Long component7() {
        return getAssigneeId();
    }

    @Override
    public Long component8() {
        return getCreatedAt();
    }

    @Override
    public Long component9() {
        return getUpdatedAt();
    }

    @Override
    public String component10() {
        return getDocumentPath();
    }

    @Override
    public String component11() {
        return getContentType();
    }

    @Override
    public String component12() {
        return getActualityStatus();
    }

    @Override
    public Double component13() {
        return getLocationLat();
    }

    @Override
    public Double component14() {
        return getLocationLon();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getDescription();
    }

    @Override
    public String value3() {
        return getStatus();
    }

    @Override
    public String value4() {
        return getPriority();
    }

    @Override
    public Long value5() {
        return getCategoryId();
    }

    @Override
    public String value6() {
        return getReporterId();
    }

    @Override
    public Long value7() {
        return getAssigneeId();
    }

    @Override
    public Long value8() {
        return getCreatedAt();
    }

    @Override
    public Long value9() {
        return getUpdatedAt();
    }

    @Override
    public String value10() {
        return getDocumentPath();
    }

    @Override
    public String value11() {
        return getContentType();
    }

    @Override
    public String value12() {
        return getActualityStatus();
    }

    @Override
    public Double value13() {
        return getLocationLat();
    }

    @Override
    public Double value14() {
        return getLocationLon();
    }

    @Override
    public IssueRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public IssueRecord value2(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public IssueRecord value3(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public IssueRecord value4(String value) {
        setPriority(value);
        return this;
    }

    @Override
    public IssueRecord value5(Long value) {
        setCategoryId(value);
        return this;
    }

    @Override
    public IssueRecord value6(String value) {
        setReporterId(value);
        return this;
    }

    @Override
    public IssueRecord value7(Long value) {
        setAssigneeId(value);
        return this;
    }

    @Override
    public IssueRecord value8(Long value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public IssueRecord value9(Long value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public IssueRecord value10(String value) {
        setDocumentPath(value);
        return this;
    }

    @Override
    public IssueRecord value11(String value) {
        setContentType(value);
        return this;
    }

    @Override
    public IssueRecord value12(String value) {
        setActualityStatus(value);
        return this;
    }

    @Override
    public IssueRecord value13(Double value) {
        setLocationLat(value);
        return this;
    }

    @Override
    public IssueRecord value14(Double value) {
        setLocationLon(value);
        return this;
    }

    @Override
    public IssueRecord values(Long value1, String value2, String value3, String value4, Long value5, String value6, Long value7, Long value8, Long value9, String value10, String value11, String value12, Double value13, Double value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IssueRecord
     */
    public IssueRecord() {
        super(Issue.ISSUE);
    }

    /**
     * Create a detached, initialised IssueRecord
     */
    public IssueRecord(Long id, String description, String status, String priority, Long categoryId, String reporterId, Long assigneeId, Long createdAt, Long updatedAt, String documentPath, String contentType, String actualityStatus, Double locationLat, Double locationLon) {
        super(Issue.ISSUE);

        setId(id);
        setDescription(description);
        setStatus(status);
        setPriority(priority);
        setCategoryId(categoryId);
        setReporterId(reporterId);
        setAssigneeId(assigneeId);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setDocumentPath(documentPath);
        setContentType(contentType);
        setActualityStatus(actualityStatus);
        setLocationLat(locationLat);
        setLocationLon(locationLon);
    }
}
