/*
 * This file is generated by jOOQ.
 */
package ru.citycheck.core.domain.db.tables.records;


import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;
import ru.citycheck.core.domain.db.tables.JwtTokens;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class JwtTokensRecord extends TableRecordImpl<JwtTokensRecord> implements Record5<String, Long, Long, String, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.jwt_tokens.jwt_token</code>.
     */
    public void setJwtToken(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.jwt_tokens.jwt_token</code>.
     */
    public String getJwtToken() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.jwt_tokens.expiration_ts</code>.
     */
    public void setExpirationTs(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.jwt_tokens.expiration_ts</code>.
     */
    public Long getExpirationTs() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.jwt_tokens.user_id</code>.
     */
    public void setUserId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.jwt_tokens.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.jwt_tokens.type</code>.
     */
    public void setType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.jwt_tokens.type</code>.
     */
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.jwt_tokens.revoked</code>.
     */
    public void setRevoked(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.jwt_tokens.revoked</code>.
     */
    public Boolean getRevoked() {
        return (Boolean) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, Long, Long, String, Boolean> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<String, Long, Long, String, Boolean> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return JwtTokens.JWT_TOKENS.JWT_TOKEN;
    }

    @Override
    public Field<Long> field2() {
        return JwtTokens.JWT_TOKENS.EXPIRATION_TS;
    }

    @Override
    public Field<Long> field3() {
        return JwtTokens.JWT_TOKENS.USER_ID;
    }

    @Override
    public Field<String> field4() {
        return JwtTokens.JWT_TOKENS.TYPE;
    }

    @Override
    public Field<Boolean> field5() {
        return JwtTokens.JWT_TOKENS.REVOKED;
    }

    @Override
    public String component1() {
        return getJwtToken();
    }

    @Override
    public Long component2() {
        return getExpirationTs();
    }

    @Override
    public Long component3() {
        return getUserId();
    }

    @Override
    public String component4() {
        return getType();
    }

    @Override
    public Boolean component5() {
        return getRevoked();
    }

    @Override
    public String value1() {
        return getJwtToken();
    }

    @Override
    public Long value2() {
        return getExpirationTs();
    }

    @Override
    public Long value3() {
        return getUserId();
    }

    @Override
    public String value4() {
        return getType();
    }

    @Override
    public Boolean value5() {
        return getRevoked();
    }

    @Override
    public JwtTokensRecord value1(String value) {
        setJwtToken(value);
        return this;
    }

    @Override
    public JwtTokensRecord value2(Long value) {
        setExpirationTs(value);
        return this;
    }

    @Override
    public JwtTokensRecord value3(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public JwtTokensRecord value4(String value) {
        setType(value);
        return this;
    }

    @Override
    public JwtTokensRecord value5(Boolean value) {
        setRevoked(value);
        return this;
    }

    @Override
    public JwtTokensRecord values(String value1, Long value2, Long value3, String value4, Boolean value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JwtTokensRecord
     */
    public JwtTokensRecord() {
        super(JwtTokens.JWT_TOKENS);
    }

    /**
     * Create a detached, initialised JwtTokensRecord
     */
    public JwtTokensRecord(String jwtToken, Long expirationTs, Long userId, String type, Boolean revoked) {
        super(JwtTokens.JWT_TOKENS);

        setJwtToken(jwtToken);
        setExpirationTs(expirationTs);
        setUserId(userId);
        setType(type);
        setRevoked(revoked);
    }
}
