/*
 * This file is generated by jOOQ.
 */
package ru.citycheck.core.domain.db;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import ru.citycheck.core.domain.db.tables.*;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[]{FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS}, false);
    public static final Index ISSUE_ASSIGNEE_ID_IDX = Internal.createIndex(DSL.name("issue_assignee_id_idx"), Issue.ISSUE, new OrderField[]{Issue.ISSUE.ASSIGNEE_ID}, false);
    public static final Index ISSUE_REPORTER_ID_IDX = Internal.createIndex(DSL.name("issue_reporter_id_idx"), Issue.ISSUE, new OrderField[]{Issue.ISSUE.REPORTER_ID}, false);
    public static final Index ISSUE_STATUS_IDX = Internal.createIndex(DSL.name("issue_status_idx"), Issue.ISSUE, new OrderField[]{Issue.ISSUE.STATUS}, false);
    public static final Index JWT_TOKENS__EXPIRATION_TS__IDX = Internal.createIndex(DSL.name("jwt_tokens__expiration_ts__idx"), JwtTokens.JWT_TOKENS, new OrderField[]{JwtTokens.JWT_TOKENS.EXPIRATION_TS}, false);
    public static final Index JWT_TOKENS__TOKEN__IDX = Internal.createIndex(DSL.name("jwt_tokens__token__idx"), JwtTokens.JWT_TOKENS, new OrderField[]{JwtTokens.JWT_TOKENS.JWT_TOKEN}, false);
    public static final Index JWT_TOKENS__USER_ID__IDX = Internal.createIndex(DSL.name("jwt_tokens__user_id__idx"), JwtTokens.JWT_TOKENS, new OrderField[]{JwtTokens.JWT_TOKENS.USER_ID}, false);
    public static final Index USER_ROLES__USER_ROLE__IDX = Internal.createIndex(DSL.name("user_roles__user_role__idx"), UserRoles.USER_ROLES, new OrderField[]{UserRoles.USER_ROLES.USER_ID, UserRoles.USER_ROLES.ROLE}, true);
    public static final Index USERS__DISABLED_USERNAME__IDX = Internal.createIndex(DSL.name("users__disabled_username__idx"), Users.USERS, new OrderField[]{Users.USERS.IS_DISABLED, Users.USERS.USERNAME}, false);
    public static final Index USERS__USERNAME__IDX = Internal.createIndex(DSL.name("users__username__idx"), Users.USERS, new OrderField[]{Users.USERS.USERNAME}, false);
}
