/*
 * This file is generated by jOOQ.
 */
package ru.citycheck.core.domain.db;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import ru.citycheck.core.domain.db.tables.FlywaySchemaHistory;
import ru.citycheck.core.domain.db.tables.JwtTokens;
import ru.citycheck.core.domain.db.tables.Users;
import ru.citycheck.core.domain.db.tables.records.FlywaySchemaHistoryRecord;
import ru.citycheck.core.domain.db.tables.records.JwtTokensRecord;
import ru.citycheck.core.domain.db.tables.records.UsersRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<JwtTokensRecord> JWT_TOKENS_JWT_TOKEN_KEY = Internal.createUniqueKey(JwtTokens.JWT_TOKENS, DSL.name("jwt_tokens_jwt_token_key"), new TableField[] { JwtTokens.JWT_TOKENS.JWT_TOKEN }, true);
    public static final UniqueKey<UsersRecord> USERS_USERNAME_KEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_username_key"), new TableField[] { Users.USERS.USERNAME }, true);
}
