/*
 * This file is generated by jOOQ.
 */
package ru.citycheck.core.domain.db.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.citycheck.core.domain.db.Keys;
import ru.citycheck.core.domain.db.Public;
import ru.citycheck.core.domain.db.tables.records.IssueDocumentRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IssueDocument extends TableImpl<IssueDocumentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.issue_document</code>
     */
    public static final IssueDocument ISSUE_DOCUMENT = new IssueDocument();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IssueDocumentRecord> getRecordType() {
        return IssueDocumentRecord.class;
    }

    /**
     * The column <code>public.issue_document.id</code>.
     */
    public final TableField<IssueDocumentRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.issue_document.document_path</code>.
     */
    public final TableField<IssueDocumentRecord, String> DOCUMENT_PATH = createField(DSL.name("document_path"), SQLDataType.VARCHAR(1024), this, "");

    /**
     * The column <code>public.issue_document.content_type</code>.
     */
    public final TableField<IssueDocumentRecord, String> CONTENT_TYPE = createField(DSL.name("content_type"), SQLDataType.VARCHAR(64), this, "");

    private IssueDocument(Name alias, Table<IssueDocumentRecord> aliased) {
        this(alias, aliased, null);
    }

    private IssueDocument(Name alias, Table<IssueDocumentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.issue_document</code> table reference
     */
    public IssueDocument(String alias) {
        this(DSL.name(alias), ISSUE_DOCUMENT);
    }

    /**
     * Create an aliased <code>public.issue_document</code> table reference
     */
    public IssueDocument(Name alias) {
        this(alias, ISSUE_DOCUMENT);
    }

    /**
     * Create a <code>public.issue_document</code> table reference
     */
    public IssueDocument() {
        this(DSL.name("issue_document"), null);
    }

    public <O extends Record> IssueDocument(Table<O> child, ForeignKey<O, IssueDocumentRecord> key) {
        super(child, key, ISSUE_DOCUMENT);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public Identity<IssueDocumentRecord, Long> getIdentity() {
        return (Identity<IssueDocumentRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<IssueDocumentRecord> getPrimaryKey() {
        return Keys.ISSUE_DOCUMENT_PKEY;
    }

    @Override
    public List<UniqueKey<IssueDocumentRecord>> getKeys() {
        return Arrays.<UniqueKey<IssueDocumentRecord>>asList(Keys.ISSUE_DOCUMENT_PKEY);
    }

    @Override
    public IssueDocument as(String alias) {
        return new IssueDocument(DSL.name(alias), this);
    }

    @Override
    public IssueDocument as(Name alias) {
        return new IssueDocument(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public IssueDocument rename(String name) {
        return new IssueDocument(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IssueDocument rename(Name name) {
        return new IssueDocument(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
