/*
 * This file is generated by jOOQ.
 */
package ru.citycheck.core.domain.db.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.citycheck.core.domain.db.Keys;
import ru.citycheck.core.domain.db.Public;
import ru.citycheck.core.domain.db.tables.records.IssueVoiceDescriptionRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IssueVoiceDescription extends TableImpl<IssueVoiceDescriptionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.issue_voice_description</code>
     */
    public static final IssueVoiceDescription ISSUE_VOICE_DESCRIPTION = new IssueVoiceDescription();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IssueVoiceDescriptionRecord> getRecordType() {
        return IssueVoiceDescriptionRecord.class;
    }

    /**
     * The column <code>public.issue_voice_description.id</code>.
     */
    public final TableField<IssueVoiceDescriptionRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.issue_voice_description.document_path</code>.
     */
    public final TableField<IssueVoiceDescriptionRecord, String> DOCUMENT_PATH = createField(DSL.name("document_path"), SQLDataType.VARCHAR(1024), this, "");

    /**
     * The column <code>public.issue_voice_description.content_type</code>.
     */
    public final TableField<IssueVoiceDescriptionRecord, String> CONTENT_TYPE = createField(DSL.name("content_type"), SQLDataType.VARCHAR(64), this, "");

    private IssueVoiceDescription(Name alias, Table<IssueVoiceDescriptionRecord> aliased) {
        this(alias, aliased, null);
    }

    private IssueVoiceDescription(Name alias, Table<IssueVoiceDescriptionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.issue_voice_description</code> table reference
     */
    public IssueVoiceDescription(String alias) {
        this(DSL.name(alias), ISSUE_VOICE_DESCRIPTION);
    }

    /**
     * Create an aliased <code>public.issue_voice_description</code> table reference
     */
    public IssueVoiceDescription(Name alias) {
        this(alias, ISSUE_VOICE_DESCRIPTION);
    }

    /**
     * Create a <code>public.issue_voice_description</code> table reference
     */
    public IssueVoiceDescription() {
        this(DSL.name("issue_voice_description"), null);
    }

    public <O extends Record> IssueVoiceDescription(Table<O> child, ForeignKey<O, IssueVoiceDescriptionRecord> key) {
        super(child, key, ISSUE_VOICE_DESCRIPTION);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public Identity<IssueVoiceDescriptionRecord, Long> getIdentity() {
        return (Identity<IssueVoiceDescriptionRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<IssueVoiceDescriptionRecord> getPrimaryKey() {
        return Keys.ISSUE_VOICE_DESCRIPTION_PKEY;
    }

    @Override
    public List<UniqueKey<IssueVoiceDescriptionRecord>> getKeys() {
        return Arrays.<UniqueKey<IssueVoiceDescriptionRecord>>asList(Keys.ISSUE_VOICE_DESCRIPTION_PKEY);
    }

    @Override
    public IssueVoiceDescription as(String alias) {
        return new IssueVoiceDescription(DSL.name(alias), this);
    }

    @Override
    public IssueVoiceDescription as(Name alias) {
        return new IssueVoiceDescription(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public IssueVoiceDescription rename(String name) {
        return new IssueVoiceDescription(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IssueVoiceDescription rename(Name name) {
        return new IssueVoiceDescription(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
